# Generated by Django 4.2 on 2023-04-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cm_id", models.CharField(max_length=200, null=True)),
                ("name", models.CharField(max_length=255, null=True)),
                ("born_date", models.DateField(null=True)),
                ("joined_date", models.DateField(null=True)),
                ("phone_number", models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pr_id", models.CharField(max_length=200, null=True)),
                ("name", models.CharField(max_length=255, null=True)),
                ("price", models.IntegerField(null=True)),
                ("origin", models.CharField(max_length=255, null=True)),
                ("image", models.ImageField(null=True, upload_to="img_product")),
            ],
        ),
    ]
