# Generated by Django 4.2 on 2023-04-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="describe",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
