# Generated by Django 4.2 on 2023-05-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_rename_customer_order_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="digital",
        ),
        migrations.AddField(
            model_name="product",
            name="classify",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
