# Generated by Django 4.2 on 2023-05-14 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_remove_product_digital_product_classify"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="order",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="product",
        ),
        migrations.RemoveField(
            model_name="shippingaddress",
            name="order",
        ),
        migrations.RemoveField(
            model_name="shippingaddress",
            name="user",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="OrderItem",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
        migrations.DeleteModel(
            name="ShippingAddress",
        ),
    ]
